language: generic
sudo: required
services:
  - docker

# Create image to run test
before_install:
  - docker build -t ayfantis53/react-test -f ./client/Dockerfile.dev ./client

# Tests
script:
  - docker run -e CI=true ayfantis53/react-test npm test

# Production images build
after_success: 
  - docker build -t ayfantis53/memories-client ./client
  - docker build -t ayfantis53/memories-nginx ./nginx
  - docker build -t ayfantis53/memories-server ./server
  # Log in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to DockerHub
  - docker push ayfantis53/memories-client 
  - docker push ayfantis53/memories-nginx
  - docker push ayfantis53/memories-server 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "memories"
  env: "Memories-env"
  bucket_name: "elasticbeanstalk-us-east-1-583762202529"
  bucket_path: "memories"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  edge: true

  # Set the security group in AWS to listen on ports 5432-6379
  # Set a bigger EC2 Instance t2-medium
  # Set environmental variables
  # Put EC2 Instances Ip address into MongoAtlas DB whitelist


