language: generic
sudo: required
services:
  - docker

# Create image to run test
before_install:
  - docker build -t ayfantis53/react-test -f ./client/Dockerfile.dev ./client

# Tests
script:
  - docker run -e CI=true ayfantis53/react-test npm test

# Production images build
after_success: 
  - docker build -t ayfantis53/multi-client -f ./client/
  - docker build -t ayfantis53/multi-nginx -f ./nginx/
  - docker build -t ayfantis53/multi-server -f ./server/
  # Log in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to DockerHub
  - docker push ayfantis53/multi-client 
  - docker push ayfantis53/ayfantis53/multi-nginx
  - docker push ayfantis53/multi-server 

