language: generic
sudo: required
services:
  - docker

# Create image to run test
before_install:
  - docker build -t ayfantis53/react-test -f ./client/Dockerfile.dev ./client

# Tests
script:
  - docker run -e CI=true ayfantis53/react-test npm test

# Production images build
after_success: 
  - docker build -t ayfantis53/memories-client ./client
  - docker build -t ayfantis53/memories-nginx ./nginx
  - docker build -t ayfantis53/memories-server ./server
  # Log in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to DockerHub
  - docker push ayfantis53/memories-client 
  - docker push ayfantis53/memories-nginx
  - docker push ayfantis53/memories-server 

