language: generic
sudo: required
services:
  - docker

# Create image to run test
before_install:
  - docker build -t ayfantis53/react-test -f ./client/Dockerfile.dev ./client

# Tests
script:
  - docker run -e CI=true ayfantis53/react-test npm test

# Production images build
after_success: 
  - docker build -t ayfantis53/memories-client ./client1
  - docker build -t ayfantis53/memories-nginx ./nginx1
  - docker build -t ayfantis53/memories-server ./server1
  # Log in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to DockerHub
  - docker push ayfantis53/memories-client1 
  - docker push ayfantis53/memories-nginx1
  - docker push ayfantis53/memories-server1 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "memories"
  env: "Memories-env"
  bucket_name: "elasticbeanstalk-us-east-1-583762202529"
  bucket_path: "memories"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  edge: true

