version: '3'
services:
  client:
    image: 'ayfantis53/memories-clien1'
    mem_limit: 128m
    hostname: client
  server:
    image: 'ayfantis53/memories-server1'
    mem_limit: 128m
    hostname: api
    ports:
      - "5000:5000"
  nginx:
    image: 'ayfantis53/memories-nginx1'
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"